# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k2K82D9DUeXImrwbCImwc8ddYzm41j75
"""



import re
import numpy as np

def read_stopwords(file_path):
    """
    Read stopwords from a file and return them as a set.
    """
    with open(file_path, 'r') as file:
        stopwords = set(file.read().splitlines())
    return stopwords

def process_text_file(file_path, stopwords):
    """
    Process the text file: read it, split into words, count occurrences,
    and exclude stopwords.
    """
    with open(file_path, 'r') as file:
        text = file.read().lower()
        # Remove characters that are not letters, apostrophes, or dashes
        words = re.findall(r"\b[\w'-]+\b", text)

    word_count = {}
    for word in words:
        if word not in stopwords:
            word_count[word] = word_count.get(word, 0) + 1

    return word_count

def assign_font_sizes(word_count, num_sizes=5):
    """
    Assign font sizes to words based on their count.
    """
    max_count = max(word_count.values())
    size_ranges = np.linspace(1, max_count, num_sizes + 1)

    # Define font sizes
    font_sizes = [10, 20, 30, 40, 50]

    for word in word_count:
        count = word_count[word]
        for i, bound in enumerate(size_ranges):
            if count <= bound:
                word_count[word] = font_sizes[i-1]
                break

    return word_count

def generate_html(word_count):
    """
    Generate HTML code for the word cloud.
    """
    body = ""
    for word, size in word_count.items():
        body += htmlhelper.make_HTML_word(word, size) + " "

    # Use a fixed width for the HTML box
    html_box = htmlhelper.make_HTML_box(body, 500)

    # Write to an output file
    with open('cloud.html', 'w') as file:
        file.write(html_box)

Main program
def main():
    stopwords_file = 'stopwords.txt'
    text_file = input("Enter the name of the text file to process: ")

    stopwords = read_stopwords(stopwords_file)
    word_count = process_text_file(text_file, stopwords)
    word_count = assign_font_sizes(word_count)
    generate_html(word_count)

# Uncomment to run the program
# main()
