# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aS1FknaqDtj6BtWZrPhRPpcf_vuv2XMG
"""

import sympy as sp

# Define symbols
x, C = sp.symbols('x C')

# Given integral expression
integral_expr = sp.integrate(x * sp.exp(1.5 * x), x)

# Given initial condition
initial_condition_x = 0.4
initial_condition_y = 4

# Solve for C using the initial condition
C_solution = sp.solve(initial_condition_y * sp.exp(1.5 * initial_condition_x) - integral_expr.subs(x, initial_condition_x) - C, C)

# Define the general solution for y(x)
y = integral_expr + C_solution[0]

# Print the general solution
print("The general solution for y(x) is:")
print(y)
