# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10LOAALjZfqQeNXybiG1sd4yPbtu8UrpW
"""

import sympy as sp

# Define symbols
p, phi, theta = sp.symbols('p phi theta')

# Define the function to integrate
f = p**2 * sp.sin(phi)

# Define the limits of integration
p_lower = 0
p_upper = 4.5 * sp.cos(phi)
phi_lower = 0
phi_upper = 0.24497
theta_lower = 0
theta_upper = 2 * sp.pi

# Perform the triple integral
result = sp.integrate(sp.integrate(sp.integrate(f, (p, p_lower, p_upper)), (phi, phi_lower, phi_upper)), (theta, theta_lower, theta_upper))
print("Result of the triple integral:", result.evalf())

import sympy as sp

# Define symbols
r, theta, z = sp.symbols('r theta z')

# Define the function to integrate
f = r

# Define the limits of integration
theta_lower = 0
theta_upper = 2 * sp.pi
r_lower = 0
r_upper = sp.sqrt(96)
z_lower = 2
z_upper = sp.sqrt(100 - r**2)

# Perform the triple integral
result = sp.integrate(sp.integrate(sp.integrate(f, (z, z_lower, z_upper)), (r, r_lower, r_upper)), (theta, theta_lower, theta_upper))
print("Result of the triple integral:", result.evalf())
