# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YVSTmdq9jGqqe8Cf9vz8PrlfQ0GLR8ot
"""

import numpy as np

# Define the function
def f(x, y):
    return x**2 - x*y + y**2 - 4*x + 4*y

# Set the range and resolution for x and y values
radius = 4
resolution = 0.1
x_values = np.arange(-radius, radius + resolution, resolution)
y_values = np.arange(-radius, radius + resolution, resolution)

# Create a meshgrid for x and y
x_grid, y_grid = np.meshgrid(x_values, y_values)

# Apply the constraint x^2 + y^2 <= 16
mask = x_grid**2 + y_grid**2 <= 16

# Calculate f(x, y) for valid points
f_values = f(x_grid, y_grid)
f_values[~mask] = np.nan  # Set values outside the circle to NaN

# Find the maximum and minimum values within the domain
f_max = np.nanmax(f_values)
f_min = np.nanmin(f_values)

print(f"The maximum value of f on the domain x^2 + y^2 <= 16 is {f_max}")
