# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1npNBC4LL18acUpxBa8h66fSar2v-966C
"""

from google.colab import files
import numpy as np
import matplotlib.pyplot as plt

# Upload the CSV file
uploaded = files.upload()

# Read the CSV file
my_file = open('Practice_18.csv')

# Part 1

import pandas as pd
import matplotlib.pyplot as plt

# Open the CSV file
df = pd.read_csv('Practice_18.csv')

# Plot the data
plt.plot(df.iloc[:, 0], df.iloc[:, 1])
plt.xlabel('X')
plt.ylabel('Y')
plt.show()

# Part 2
# Create list1 and list2
list1 = df.iloc[:, 0].tolist()
list2 = df.iloc[:, 1].tolist()

# Add odd numbers to list1
new_list1 = []
for i in range(len(list1)):
    new_list1.append(list1[i])
    if i < len(list1) - 1:
        new_list1.append(list1[i] + 1)

# Find the average value for the missing position in list2
missing_index = new_list1.index(11.0)
average_value = (list2[missing_index - 1] + list2[missing_index + 1]) / 2
list2.insert(missing_index, average_value)

# Plot the new graph
plt.plot(new_list1, list2)
plt.xlabel('X')
plt.ylabel('Y')
plt.show()

# Part 3

# Prompt user for the starting point on the x-axis
user_input = float(input('Enter the start point of the plot from 10 to 198:\n'))

# Search list1 for the closest x value to the user's input
closest_value = min(list1, key=lambda x: abs(x - user_input))
if 10 <= closest_value <= 198:
    # Plot data from the closest value to the user input till the end
    start_index = list1.index(closest_value)
    plt.figure(figsize=(6, 4))
    plt.plot(list1[start_index:], list2[start_index:])
    plt.xlabel('X')
    plt.ylabel('Y')
    plt.title(f'Plot beginning from {closest_value}')
    plt.show()
