# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VfXQS6zBw584WzZLTnchsIrsglM3kM8P
"""

import numpy as np
from scipy.integrate import quad

# Define the integrand function
def integrand(t):
    return (10 * np.sin(5 * t) + 6 * np.cos(5 * t)) * np.sqrt(2500 - 1600 * np.sin(5 * t)**2)

# Compute the integral
result, error = quad(integrand, 0, np.pi)
result
