# -*- coding: utf-8 -*-
"""problem 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1caFWZ1_PZ3BTJAMqGkJ1tw6IBjLc3Ntm
"""

def sum_average():
  '''
  @file name: Practice_problem_6
  @date created: 10/04/2023
  @version: 1.00
  '''
  total = 0
  count = 0
  while True:
    enter_number = input('Enter a number or say stop ')
    if enter_number.lower() == 'stop':
      break
    enter_number = int(enter_number)
    total = total + enter_number
    count = count + 1
  if count > 0:
    average = total / count
  else:
    average = 0
  print(f'The total sum is {total} and the average is {average:.2f}')
  if average < 0:
    print('The average is negative')
  elif 0 < average < 100:
    print('The average is low')
  else:
    print('The average is high')
  return total, average
sum_average()