# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1muhqt5R-yfkMwXzOrs1FKuKE7ic5-NMN
"""

import numpy as np
import matplotlib.pyplot as plt

# Define the function
def f(x, y, z):
    return x**2 + y**2 + z**2

# Generate x and y values
x = np.linspace(-5, 5, 100)
y = np.linspace(-5, 5, 100)

# Create a meshgrid
X, Y = np.meshgrid(x, y)

# Set z = 0 for simplicity (you can change this if desired)
z = 0

# Compute the values of f(x, y, z)
Z = f(X, Y, z)

# Plot the contour map
plt.figure(figsize=(8, 6))
contour = plt.contour(X, Y, Z, cmap='viridis')
plt.colorbar(contour, label='f(x, y, z)')
plt.title('Contour Map for f(x, y, z) = x^2 + y^2 + z^2')
plt.xlabel('x')
plt.ylabel('y')
plt.grid(True)
plt.show()