# -*- coding: utf-8 -*-
"""untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S_kufbfj9hG4CItwqMs_7lK7GnHeICgD
"""

'''
@filename: PA3
@author: Qianxun Tu
@description: Create dictionary record and nested dictionary file for each
student grades, and give each user ability to search for student records and
printing course grades. Then we giver user ability to add a student in the list,
we further give access to the user to modify the list for homework grade,
midterm and final scores. We give the user 5 number option and for each they
enter it returns a paired diction.
@date: 11/17/2023
@version: 1.00
'''
#Part 1

from google.colab import drive
drive.mount('/content/drive')

import csv

my_file = open('/content/drive//MyDrive/grades.csv')

# Part 5: Search or add a student in 'records' and add course details
choice = input('1: Search for a student, 2: Add a student: ')

if choice == '1':
    student_name = input('Type in student name: ')
    if student_name in records:
        student_courses = records[student_name]
        for course, grades in student_courses.items():
            print(f'{course}: {grades}')
    else:
        print('Student not in our records.')
elif choice == '2':
    student_name = input('Type in student name: ')
    if student_name in records:
        print('Student already in the records.')
    else:
        course_name = input('Type in course name: ')
        homework_grade = float(input('Type in homework grade: '))
        midterm_grade = float(input('Type in midterm grade: '))
        final_grade = float(input('Type in final grade: '))

        course = {'homework': homework_grade, 'midterm': midterm_grade, 'final': final_grade}
        records[student_name] = {course_name: course}
else:
    print('Invalid choice.')

# Part 6: Modify a student's record in 'records'
choice = input('1: Search for a student, 2: Add a student, 3: Modify a student record: ')

if choice == '1':
    student_name = input('Type in student name: ')
    if student_name in records:
        student_courses = records[student_name]
        for course, grades in student_courses.items():
            print(f'{course}: {grades}')
    else:
        print('Student not in our records.')
elif choice == '2':
    student_name = input('Type in student name: ')
    if student_name in records:
        print('Student already in the records.')
    else:
        course_name = input('Type in course name: ')
        homework_grade = float(input('Type in homework grade: '))
        midterm_grade = float(input('Type in midterm grade: '))
        final_grade = float(input('Type in final grade: '))

        course = {'homework': homework_grade, 'midterm': midterm_grade, 'final': final_grade}
        records[student_name] = {course_name: course}
elif choice == '3':
    student_name = input('Type in student name: ')
    if student_name in records:
        modify_choice = input('1: Modify course details, 2: Add a new course: ')
        if modify_choice == '1':
            course_name = input('Type in course name: ')
            if course_name in records[student_name]:
                homework_grade = float(input('Type in homework grade: '))
                midterm_grade = float(input('Type in midterm grade: '))
                final_grade = float(input('Type in final grade: '))

                course = {'homework': homework_grade, 'midterm': midterm_grade, 'final': final_grade}
                records[student_name][course_name] = course
            else:
                print('Course not found.')
        elif modify_choice == '2':
            course_name = input('Type in course name: ')
            homework_grade = float(input('Type in homework grade: '))
            midterm_grade = float(input('Type in midterm grade: '))
            final_grade = float(input('Type in final grade: '))

            course = {'homework': homework_grade, 'midterm': midterm_grade, 'final': final_grade}
            records[student_name][course_name] = course
        else:
            print('Invalid choice.')
    else:
        print('Student not in our records.')
else:
    print('Invalid choice.')