# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12gieZ7VfqdRFTU0mxr_jiPBLGtM0Gp--
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Define the cylinder z^2 + y^2 = 1
theta = np.linspace(0, 2 * np.pi, 100)
z = np.linspace(-1, 1, 100)
theta, z = np.meshgrid(theta, z)
y = np.cos(theta) * np.sqrt(1 - z**2)
z = np.sin(theta) * np.sqrt(1 - z**2)
x = np.zeros_like(theta)  # x is zero along the surface of the cylinder

# Plot the cylinder
ax.plot_surface(x, y, z, color='blue', alpha=0.5, label='Cylinder: $z^2 + y^2 = 1$')

# Plot the plane x = 0
X0 = np.array([[0, 0], [0, 0]])
Y0 = np.array([[-1, 1], [-1, 1]])
Z0 = np.array([[-1, -1], [1, 1]])
ax.plot_surface(X0, Y0, Z0, alpha=0.5, color='green', label='Plane: $x = 0$')

# Plot the plane x + y + z = 10
x = np.linspace(0, 10, 100)
y = np.linspace(-1, 1, 100)
x, y = np.meshgrid(x, y)
z = 10 - x - y
ax.plot_surface(x, y, z, alpha=0.5, color='red', label='Plane: $x + y + z = 10$')

# Axes and labels
ax.set_xlabel('X axis')
ax.set_ylabel('Y axis')
ax.set_zlabel('Z axis')
ax.set_title('Visualization of the Integration Region')

# Legend and plot
plt.legend()
plt.show()