# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OpjK4pFRc6IFme7XEjdFc0q5ZgiwESy8
"""

import numpy as np
import matplotlib.pyplot as plt

# Define the range for x
x = np.linspace(-3, 1, 400)

# Define the equations
y1 = x**2 + 2*x + 1
y2 = -x**2 - 3*x + 4

# Find points of intersection by solving the equations simultaneously
intersection_x = np.roots([1, 5, -3])  # Coefficients of the difference between y1 and y2
intersection_y = intersection_x**2 + 2*intersection_x + 1  # Using y1 or y2 as they are equal at the intersection points

# Plot the equations
plt.plot(x, y1, label='y = x^2 + 2x + 1')
plt.plot(x, y2, label='y = -x^2 - 3x + 4')

# Fill the area of overlap
plt.fill_between(x, y1, y2, where=(y1 >= y2), color='lightgray', alpha=0.5)

# Plot intersection points
plt.plot(intersection_x, intersection_y, 'ro', label='Intersection Points')

# Set labels and title
plt.xlabel('x')
plt.ylabel('y')
plt.title('Area of Overlap Between Curves')
plt.legend()

# Show the plot
plt.grid(True)
plt.axhline(0, color='black',linewidth=0.5)
plt.axvline(0, color='black',linewidth=0.5)
plt.show()

