# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cmgzhyx19PK9Pn_qnCcZaO_P0AEJzBbD
"""

from scipy.optimize import fsolve
import numpy as np

# Define the function we want to solve
def equation(t):
    return 25/2 * np.exp(-20*t) - 5/2 * np.exp(-1*t) - 0.1

# Initial guess for t
initial_guess = 1

# Use fsolve to find the root
t_solution = fsolve(equation, initial_guess)

print("The solution is t =", t_solution[0])