# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g1LBjoFqhkFHpsC4oeu44UgCg5tMtC7f
"""

htmlhelper= ("/content/drive/MyDrive/htmlhelper.py")
stopwords_file_path = "/content/drive/MyDrive/stopwords.txt"
Greta_thunber= ("/content/drive/MyDrive/Greta_Thunberg_2019.txt")

import re
import htmlhelper

def read_stopwords(file_path):
    """
    Reads a list of stopwords from a file and returns them as a set.
    """
    stopwords = set()
    with open(file_path, 'r') as file:
        for line in file:
            stopwords.add(line.strip().lower())
    return stopwords

def process_text(file_path, stopwords):
    """
    Processes the text file: reads it, splits into words, counts occurrences, and excludes stopwords.
    """
    word_count = {}
    with open(file_path, 'r') as file:
        for line in file:
            words = re.findall(r"\b[\w'-]+\b", line.lower())
            for word in words:
                if word not in stopwords:
                    word_count[word] = word_count.get(word, 0) + 1
    return word_count

def assign_font_sizes(word_count, num_sizes=5):
    """
    Assigns font sizes to words based on their count.
    """
    max_count = max(word_count.values())
    bucket_size = max_count / num_sizes
    font_sizes = [14, 18, 22, 28, 34]  # Adjusted for better readability

    word_font_size = {}
    for word, count in word_count.items():
        font_size_index = min(int(count / bucket_size), num_sizes - 1)
        word_font_size[word] = font_sizes[font_size_index]

    return word_font_size

def generate_html(word_font_size):
    """
    Generates HTML code for the word cloud.
    """
    body = ""
    for word, size in word_font_size.items():
        body += htmlhelper.make_HTML_word(word, size) + " "
    return htmlhelper.make_HTML_box(body, 500)

def main():
    stopwords_file = input("Enter the stopwords file name: ")
    text_file = input("Enter the name of the text file to process: ")

    stopwords = read_stopwords(stopwords_file)
    word_count = process_text(text_file, stopwords)
    word_font_size = assign_font_sizes(word_count)
    html_code = generate_html(word_font_size)

    with open("cloud.html", 'w') as file:
        file.write(html_code)
    print("Word cloud generated in 'cloud.html'.")

if __name__ == "__main__":
    main()

from google.colab import drive
drive.mount('/content/drive')