# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v2ivZdmMCd6UBdEui0d134Ow2ogtjGV3
"""

from google.colab import files
uploaded= files.upload()
file= open(f'pride.txt')
string = file.read()
string = string.replace('\n', '')
string = string.replace(' ', '')
string_compressed = string



max_count= 0 # count the max occurring 3-letter substings
max_sub = ''
for i in range(len(string_compressed)-2):
  sub_str= string_compressed[i:i+3]
  count_list.append(sub_str) # list with all 3-letter substrings


  my_set = set(count_list) # convert the list to set. The set has unique 3-
letter substrings


print(my_set)
for sub_string in my_set:
count=count_list.count(sub_string)
if count> max_count:
max_count = count
max_sub = sub_string
print(f'three letter sub "{max_sub}" has occurred {max_count} times')



my_string = my_string.remove {"", "\n"}
word_to_search = "the"
counter = 0

for j in range(len(my_string) - 2):
        sub_string =  string[j:j+3]
        list2.append(sub_string)
print(list 2)
print("Occurrences of 'the':", counter)


list2 = []
for j in range(len(stringq)-2):
    sub_string = string[j:j+3]
    list2.append(sub_string)
print(list 2)
set1 = set(list2)
print(set1)
max_substring = ''
max_count = 0
for substring in set1:
    sub_count = list2.count(substring)
    if sub_count = list2.count(substring)
    if sub_count > max_count:
        max_count = sub_count
        max_substring = substring

my_long_dictionary = ['John': '1234','Mary': '3456']
print(my_dictionary [Mary'])
my_dictionary= ['James']='!@#$%'
print(my_dictionary)
my_dictionary['James']='12345'
print(my_dictionary)

My.dict.clear()
my.dict = {'coursel': 'CPCS1220'}
print(my_dict.get(course2'))
A= list(my_dict.items())
print(f'list of keys value tuples= {A}')
print(A[1])
sring1 = 'alad'
B= list()
print()

'
print(my_dict.get[course1])
my.dict.clear()
print(my.dict()
dict2=()

                           )