# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZTJ0KLGJXC5Ru7SJ4PVBCjvFuk9zWIJe
"""

from sympy import simplify, Eq, symbols

# Define the symbol
s = symbols('s')

# Define the expressions
lhs_expr = 1/(25_000_000 * s) - s / (25_000_000 * (s**2 + 6_000 * s + 25_000_000)) - 0.00024 / (s**2 + 6_000 * s + 25_000_000)

rhs_expr = 10**(-8) * (4/s - 4*(s + 3_000)/((s + 3_000)**2 + 4_000**2) + 3*4_000/((s + 3_000)**2 + 4_000**2))

# Simplify both expressions
simplified_lhs_expr = simplify(lhs_expr)
simplified_rhs_expr = simplify(rhs_expr)

# Check if the simplified expressions are equal
simplified_lhs_expr, simplified_rhs_expr, Eq(simplified_lhs_expr, simplified_rhs_expr)