# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lO1O9XaBRtugEgBhYuIWl0qqwAx1gv2D
"""

class travel:
  cost_per_gallon= 5.3

  def_init_(self,mph,mpg,dist):
    self.mph = mph
    self.mpg =mpg
    self.dist = dist
  def_travel_cost(self):
    time= self.dist/self.mph
    gas = self.dist/self.mpg
    gas_cost= gas * self.cos_per_gallon
  def_travel_time(self):
    self.time = self.dist/self.mph
  def_str_(self):
    #return f'Cost is {self.gas.cost} and it takes {self.time:.2f}
    print(f'gas cost is {gas_cost} dollars and it takes {time.2f} hours.')

my_travel =  travel(60, 25, 500)
my_travel.travek
my_travel.travel_cost()
my_travel.travel_time ()