# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vyvnUZcjHLu_qBE83Cjw5kN_ltyohXqc
"""

import numpy as np
from scipy.optimize import fsolve

# Define the function for which we want to find the root
def displacement(t):
    return (-5/2 *-10)* np.exp(-20*t) + (25/2*-2) * np.exp(-1*t) - 0.1

# Initial guess for the value of t
initial_guess = 0.1

# Use fsolve to find the time t
t_solution = fsolve(displacement, initial_guess)

# Print the solution for t
print("The value of t when the displacement is 0.1 mm is approximately:", t_solution[0])