# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ft2wuPMoLisp3zC65LQGy-u-FBqcGxiB
"""

from sympy import symbols, Function, Eq, dsolve, sin

# Define the symbols
p = symbols('p')
s = Function('s')(p)

# Define the differential equation
eqn = Eq((p**2-81)*s.diff(p, p, p, p) + p**4*s.diff(p, p, p) + (1/(p**2+1))*s.diff(p) + s, np.sin(p))

# Define the boundary conditions
boundary_conditions = {
    s.subs(p, 3): -15,
    s.diff(p).subs(p, 3): 5,
    s.diff(p, p).subs(p, 3): 8,
    s.diff(p, p, p).subs(p, 3): 9
}

# Solve the differential equation
sol = dsolve(eqn, ics=boundary_conditions)