# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b_8I-yhd2YTW6idnZgwnJQGGM7-MVEGh
"""

text ='This is a very important message'
print(text)
key= 3 #this should be selcted by the user
secret_text =''
for i in text:
  if i==' ': # don't cipher spaces, leave spaces in between words
     secrect_text +=1
  else:
    secret_text as chr(ord(i)+key)
print(secrect_text)
#now take the secrete text and convert it back
returned_text= ''
for i in secret_text:
  if i == ' ':
    returned_text+=1
  else:
    returned_text +=chr(ord(j)-key)
print(returned_text)

class encrypt:
    def __init__(self, secret_key=1):
        self.secret_key = max(1, min(secret_key, 6))

    def cipher(self, user_str):
        ciphered_string = ''
        for char in user_str:
            if char == ' ':
                ciphered_string += char
            else:
                ascii_val = ord(char)
                if char.isalpha():
                    ascii_val = (ascii_val - ord('a') + self.secret_key) % 26 + ord('a')
                ciphered_string += chr(ascii_val)
        return ciphered_string

    def decipher(self, ciphered_str):
        returned_text = ''
        for char in ciphered_str:
            if char == ' ':
                returned_text += char
            else:
                ascii_val = ord(char)
                if char.isalpha():
                    ascii_val = (ascii_val - ord('a') - self.secret_key) % 26 + ord('a')
                returned_text += chr(ascii_val)
        return returned_text


user_message = "This is a test for checking zzzzero"
secret_key = 3

encryptor = encrypt(secret_key)

ciphered_message = encryptor.cipher(user_message)
print("Ciphered message:", ciphered_message)

deciphered_message = encryptor.decipher(ciphered_message)
print("Deciphered message:", deciphered_message)